/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SearchRouteImport } from './routes/search'
import { Route as CheckoutRouteImport } from './routes/checkout'
import { Route as CartRouteImport } from './routes/cart'
import { Route as AccountRouteImport } from './routes/account'
import { Route as TenantRouteRouteImport } from './routes/tenant/route'
import { Route as OwnerRouteRouteImport } from './routes/owner/route'
import { Route as AgentRouteRouteImport } from './routes/agent/route'
import { Route as AdminRouteRouteImport } from './routes/admin/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as TenantIndexRouteImport } from './routes/tenant/index'
import { Route as OwnerIndexRouteImport } from './routes/owner/index'
import { Route as BundlesIndexRouteImport } from './routes/bundles/index'
import { Route as AgentIndexRouteImport } from './routes/agent/index'
import { Route as AdminIndexRouteImport } from './routes/admin/index'
import { Route as TenantRentRouteImport } from './routes/tenant/rent'
import { Route as TenantNotificationsRouteImport } from './routes/tenant/notifications'
import { Route as TenantMoveInRouteImport } from './routes/tenant/move-in'
import { Route as TenantMaintenanceRouteImport } from './routes/tenant/maintenance'
import { Route as TenantDocumentsRouteImport } from './routes/tenant/documents'
import { Route as TenantComplaintsRouteImport } from './routes/tenant/complaints'
import { Route as PropertySlugRouteImport } from './routes/property/$slug'
import { Route as ProductSlugRouteImport } from './routes/product/$slug'
import { Route as PagesSlugRouteImport } from './routes/pages/$slug'
import { Route as OwnerStatementsRouteImport } from './routes/owner/statements'
import { Route as OwnerPortfolioRouteImport } from './routes/owner/portfolio'
import { Route as OwnerMaintenanceRouteImport } from './routes/owner/maintenance'
import { Route as CollectionSlugRouteImport } from './routes/collection/$slug'
import { Route as CheckoutSuccessRouteImport } from './routes/checkout/success'
import { Route as BundleSlugRouteImport } from './routes/bundle/$slug'
import { Route as AgentViewingsRouteImport } from './routes/agent/viewings'
import { Route as AgentTenantsRouteImport } from './routes/agent/tenants'
import { Route as AgentMaintenanceRouteImport } from './routes/agent/maintenance'
import { Route as AgentInquiriesRouteImport } from './routes/agent/inquiries'
import { Route as AdminUsersRouteImport } from './routes/admin/users'
import { Route as AdminTenancyRouteImport } from './routes/admin/tenancy'
import { Route as AdminSubmissionsRouteImport } from './routes/admin/submissions'
import { Route as AdminSiteSettingsRouteImport } from './routes/admin/site-settings'
import { Route as AdminSettingsRouteImport } from './routes/admin/settings'
import { Route as AdminRealEstateRouteImport } from './routes/admin/real-estate'
import { Route as AdminProductsRouteImport } from './routes/admin/products'
import { Route as AdminPagesRouteImport } from './routes/admin/pages'
import { Route as AdminOrdersRouteImport } from './routes/admin/orders'
import { Route as AdminNewsletterRouteImport } from './routes/admin/newsletter'
import { Route as AdminNavLinksRouteImport } from './routes/admin/nav-links'
import { Route as AdminMediaRouteImport } from './routes/admin/media'
import { Route as AdminLoginRouteImport } from './routes/admin/login'
import { Route as AdminLifestyleCardsRouteImport } from './routes/admin/lifestyle-cards'
import { Route as AdminIntegrationsRouteImport } from './routes/admin/integrations'
import { Route as AdminHomepageSectionsRouteImport } from './routes/admin/homepage-sections'
import { Route as AdminHomepageRouteImport } from './routes/admin/homepage'
import { Route as AdminHeroSlidesRouteImport } from './routes/admin/hero-slides'
import { Route as AdminFeatureCardsRouteImport } from './routes/admin/feature-cards'
import { Route as AdminEmailTemplatesRouteImport } from './routes/admin/email-templates'
import { Route as AdminDataTransferRouteImport } from './routes/admin/data-transfer'
import { Route as AdminContentRouteImport } from './routes/admin/content'
import { Route as AdminCommunicationsRouteImport } from './routes/admin/communications'
import { Route as AdminCommerceRouteImport } from './routes/admin/commerce'
import { Route as AdminCollectionsRouteImport } from './routes/admin/collections'
import { Route as AdminCheckoutRouteImport } from './routes/admin/checkout'
import { Route as AdminCategoriesRouteImport } from './routes/admin/categories'
import { Route as AdminCatalogRouteImport } from './routes/admin/catalog'
import { Route as AccountProfileRouteImport } from './routes/account/profile'
import { Route as AccountNotificationsRouteImport } from './routes/account/notifications'
import { Route as AgentTransactionsIndexRouteImport } from './routes/agent/transactions/index'
import { Route as AccountViewingsIndexRouteImport } from './routes/account/viewings/index'
import { Route as AccountTransactionsIndexRouteImport } from './routes/account/transactions/index'
import { Route as AgentTransactionsTransactionIdRouteImport } from './routes/agent/transactions/$transactionId'
import { Route as AccountTransactionsTransactionIdRouteImport } from './routes/account/transactions/$transactionId'
import { Route as AccountOrdersOrderIdRouteImport } from './routes/account/orders/$orderId'

const SearchRoute = SearchRouteImport.update({
  id: '/search',
  path: '/search',
  getParentRoute: () => rootRouteImport,
} as any)
const CheckoutRoute = CheckoutRouteImport.update({
  id: '/checkout',
  path: '/checkout',
  getParentRoute: () => rootRouteImport,
} as any)
const CartRoute = CartRouteImport.update({
  id: '/cart',
  path: '/cart',
  getParentRoute: () => rootRouteImport,
} as any)
const AccountRoute = AccountRouteImport.update({
  id: '/account',
  path: '/account',
  getParentRoute: () => rootRouteImport,
} as any)
const TenantRouteRoute = TenantRouteRouteImport.update({
  id: '/tenant',
  path: '/tenant',
  getParentRoute: () => rootRouteImport,
} as any)
const OwnerRouteRoute = OwnerRouteRouteImport.update({
  id: '/owner',
  path: '/owner',
  getParentRoute: () => rootRouteImport,
} as any)
const AgentRouteRoute = AgentRouteRouteImport.update({
  id: '/agent',
  path: '/agent',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRouteRoute = AdminRouteRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const TenantIndexRoute = TenantIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => TenantRouteRoute,
} as any)
const OwnerIndexRoute = OwnerIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => OwnerRouteRoute,
} as any)
const BundlesIndexRoute = BundlesIndexRouteImport.update({
  id: '/bundles/',
  path: '/bundles/',
  getParentRoute: () => rootRouteImport,
} as any)
const AgentIndexRoute = AgentIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AgentRouteRoute,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRouteRoute,
} as any)
const TenantRentRoute = TenantRentRouteImport.update({
  id: '/rent',
  path: '/rent',
  getParentRoute: () => TenantRouteRoute,
} as any)
const TenantNotificationsRoute = TenantNotificationsRouteImport.update({
  id: '/notifications',
  path: '/notifications',
  getParentRoute: () => TenantRouteRoute,
} as any)
const TenantMoveInRoute = TenantMoveInRouteImport.update({
  id: '/move-in',
  path: '/move-in',
  getParentRoute: () => TenantRouteRoute,
} as any)
const TenantMaintenanceRoute = TenantMaintenanceRouteImport.update({
  id: '/maintenance',
  path: '/maintenance',
  getParentRoute: () => TenantRouteRoute,
} as any)
const TenantDocumentsRoute = TenantDocumentsRouteImport.update({
  id: '/documents',
  path: '/documents',
  getParentRoute: () => TenantRouteRoute,
} as any)
const TenantComplaintsRoute = TenantComplaintsRouteImport.update({
  id: '/complaints',
  path: '/complaints',
  getParentRoute: () => TenantRouteRoute,
} as any)
const PropertySlugRoute = PropertySlugRouteImport.update({
  id: '/property/$slug',
  path: '/property/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const ProductSlugRoute = ProductSlugRouteImport.update({
  id: '/product/$slug',
  path: '/product/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const PagesSlugRoute = PagesSlugRouteImport.update({
  id: '/pages/$slug',
  path: '/pages/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const OwnerStatementsRoute = OwnerStatementsRouteImport.update({
  id: '/statements',
  path: '/statements',
  getParentRoute: () => OwnerRouteRoute,
} as any)
const OwnerPortfolioRoute = OwnerPortfolioRouteImport.update({
  id: '/portfolio',
  path: '/portfolio',
  getParentRoute: () => OwnerRouteRoute,
} as any)
const OwnerMaintenanceRoute = OwnerMaintenanceRouteImport.update({
  id: '/maintenance',
  path: '/maintenance',
  getParentRoute: () => OwnerRouteRoute,
} as any)
const CollectionSlugRoute = CollectionSlugRouteImport.update({
  id: '/collection/$slug',
  path: '/collection/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const CheckoutSuccessRoute = CheckoutSuccessRouteImport.update({
  id: '/success',
  path: '/success',
  getParentRoute: () => CheckoutRoute,
} as any)
const BundleSlugRoute = BundleSlugRouteImport.update({
  id: '/bundle/$slug',
  path: '/bundle/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const AgentViewingsRoute = AgentViewingsRouteImport.update({
  id: '/viewings',
  path: '/viewings',
  getParentRoute: () => AgentRouteRoute,
} as any)
const AgentTenantsRoute = AgentTenantsRouteImport.update({
  id: '/tenants',
  path: '/tenants',
  getParentRoute: () => AgentRouteRoute,
} as any)
const AgentMaintenanceRoute = AgentMaintenanceRouteImport.update({
  id: '/maintenance',
  path: '/maintenance',
  getParentRoute: () => AgentRouteRoute,
} as any)
const AgentInquiriesRoute = AgentInquiriesRouteImport.update({
  id: '/inquiries',
  path: '/inquiries',
  getParentRoute: () => AgentRouteRoute,
} as any)
const AdminUsersRoute = AdminUsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminTenancyRoute = AdminTenancyRouteImport.update({
  id: '/tenancy',
  path: '/tenancy',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminSubmissionsRoute = AdminSubmissionsRouteImport.update({
  id: '/submissions',
  path: '/submissions',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminSiteSettingsRoute = AdminSiteSettingsRouteImport.update({
  id: '/site-settings',
  path: '/site-settings',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminSettingsRoute = AdminSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminRealEstateRoute = AdminRealEstateRouteImport.update({
  id: '/real-estate',
  path: '/real-estate',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminProductsRoute = AdminProductsRouteImport.update({
  id: '/products',
  path: '/products',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminPagesRoute = AdminPagesRouteImport.update({
  id: '/pages',
  path: '/pages',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminOrdersRoute = AdminOrdersRouteImport.update({
  id: '/orders',
  path: '/orders',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminNewsletterRoute = AdminNewsletterRouteImport.update({
  id: '/newsletter',
  path: '/newsletter',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminNavLinksRoute = AdminNavLinksRouteImport.update({
  id: '/nav-links',
  path: '/nav-links',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminMediaRoute = AdminMediaRouteImport.update({
  id: '/media',
  path: '/media',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminLoginRoute = AdminLoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminLifestyleCardsRoute = AdminLifestyleCardsRouteImport.update({
  id: '/lifestyle-cards',
  path: '/lifestyle-cards',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminIntegrationsRoute = AdminIntegrationsRouteImport.update({
  id: '/integrations',
  path: '/integrations',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminHomepageSectionsRoute = AdminHomepageSectionsRouteImport.update({
  id: '/homepage-sections',
  path: '/homepage-sections',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminHomepageRoute = AdminHomepageRouteImport.update({
  id: '/homepage',
  path: '/homepage',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminHeroSlidesRoute = AdminHeroSlidesRouteImport.update({
  id: '/hero-slides',
  path: '/hero-slides',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminFeatureCardsRoute = AdminFeatureCardsRouteImport.update({
  id: '/feature-cards',
  path: '/feature-cards',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminEmailTemplatesRoute = AdminEmailTemplatesRouteImport.update({
  id: '/email-templates',
  path: '/email-templates',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminDataTransferRoute = AdminDataTransferRouteImport.update({
  id: '/data-transfer',
  path: '/data-transfer',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminContentRoute = AdminContentRouteImport.update({
  id: '/content',
  path: '/content',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminCommunicationsRoute = AdminCommunicationsRouteImport.update({
  id: '/communications',
  path: '/communications',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminCommerceRoute = AdminCommerceRouteImport.update({
  id: '/commerce',
  path: '/commerce',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminCollectionsRoute = AdminCollectionsRouteImport.update({
  id: '/collections',
  path: '/collections',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminCheckoutRoute = AdminCheckoutRouteImport.update({
  id: '/checkout',
  path: '/checkout',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminCategoriesRoute = AdminCategoriesRouteImport.update({
  id: '/categories',
  path: '/categories',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminCatalogRoute = AdminCatalogRouteImport.update({
  id: '/catalog',
  path: '/catalog',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AccountProfileRoute = AccountProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => AccountRoute,
} as any)
const AccountNotificationsRoute = AccountNotificationsRouteImport.update({
  id: '/notifications',
  path: '/notifications',
  getParentRoute: () => AccountRoute,
} as any)
const AgentTransactionsIndexRoute = AgentTransactionsIndexRouteImport.update({
  id: '/transactions/',
  path: '/transactions/',
  getParentRoute: () => AgentRouteRoute,
} as any)
const AccountViewingsIndexRoute = AccountViewingsIndexRouteImport.update({
  id: '/viewings/',
  path: '/viewings/',
  getParentRoute: () => AccountRoute,
} as any)
const AccountTransactionsIndexRoute =
  AccountTransactionsIndexRouteImport.update({
    id: '/transactions/',
    path: '/transactions/',
    getParentRoute: () => AccountRoute,
  } as any)
const AgentTransactionsTransactionIdRoute =
  AgentTransactionsTransactionIdRouteImport.update({
    id: '/transactions/$transactionId',
    path: '/transactions/$transactionId',
    getParentRoute: () => AgentRouteRoute,
  } as any)
const AccountTransactionsTransactionIdRoute =
  AccountTransactionsTransactionIdRouteImport.update({
    id: '/transactions/$transactionId',
    path: '/transactions/$transactionId',
    getParentRoute: () => AccountRoute,
  } as any)
const AccountOrdersOrderIdRoute = AccountOrdersOrderIdRouteImport.update({
  id: '/orders/$orderId',
  path: '/orders/$orderId',
  getParentRoute: () => AccountRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteRouteWithChildren
  '/agent': typeof AgentRouteRouteWithChildren
  '/owner': typeof OwnerRouteRouteWithChildren
  '/tenant': typeof TenantRouteRouteWithChildren
  '/account': typeof AccountRouteWithChildren
  '/cart': typeof CartRoute
  '/checkout': typeof CheckoutRouteWithChildren
  '/search': typeof SearchRoute
  '/account/notifications': typeof AccountNotificationsRoute
  '/account/profile': typeof AccountProfileRoute
  '/admin/catalog': typeof AdminCatalogRoute
  '/admin/categories': typeof AdminCategoriesRoute
  '/admin/checkout': typeof AdminCheckoutRoute
  '/admin/collections': typeof AdminCollectionsRoute
  '/admin/commerce': typeof AdminCommerceRoute
  '/admin/communications': typeof AdminCommunicationsRoute
  '/admin/content': typeof AdminContentRoute
  '/admin/data-transfer': typeof AdminDataTransferRoute
  '/admin/email-templates': typeof AdminEmailTemplatesRoute
  '/admin/feature-cards': typeof AdminFeatureCardsRoute
  '/admin/hero-slides': typeof AdminHeroSlidesRoute
  '/admin/homepage': typeof AdminHomepageRoute
  '/admin/homepage-sections': typeof AdminHomepageSectionsRoute
  '/admin/integrations': typeof AdminIntegrationsRoute
  '/admin/lifestyle-cards': typeof AdminLifestyleCardsRoute
  '/admin/login': typeof AdminLoginRoute
  '/admin/media': typeof AdminMediaRoute
  '/admin/nav-links': typeof AdminNavLinksRoute
  '/admin/newsletter': typeof AdminNewsletterRoute
  '/admin/orders': typeof AdminOrdersRoute
  '/admin/pages': typeof AdminPagesRoute
  '/admin/products': typeof AdminProductsRoute
  '/admin/real-estate': typeof AdminRealEstateRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/admin/site-settings': typeof AdminSiteSettingsRoute
  '/admin/submissions': typeof AdminSubmissionsRoute
  '/admin/tenancy': typeof AdminTenancyRoute
  '/admin/users': typeof AdminUsersRoute
  '/agent/inquiries': typeof AgentInquiriesRoute
  '/agent/maintenance': typeof AgentMaintenanceRoute
  '/agent/tenants': typeof AgentTenantsRoute
  '/agent/viewings': typeof AgentViewingsRoute
  '/bundle/$slug': typeof BundleSlugRoute
  '/checkout/success': typeof CheckoutSuccessRoute
  '/collection/$slug': typeof CollectionSlugRoute
  '/owner/maintenance': typeof OwnerMaintenanceRoute
  '/owner/portfolio': typeof OwnerPortfolioRoute
  '/owner/statements': typeof OwnerStatementsRoute
  '/pages/$slug': typeof PagesSlugRoute
  '/product/$slug': typeof ProductSlugRoute
  '/property/$slug': typeof PropertySlugRoute
  '/tenant/complaints': typeof TenantComplaintsRoute
  '/tenant/documents': typeof TenantDocumentsRoute
  '/tenant/maintenance': typeof TenantMaintenanceRoute
  '/tenant/move-in': typeof TenantMoveInRoute
  '/tenant/notifications': typeof TenantNotificationsRoute
  '/tenant/rent': typeof TenantRentRoute
  '/admin/': typeof AdminIndexRoute
  '/agent/': typeof AgentIndexRoute
  '/bundles/': typeof BundlesIndexRoute
  '/owner/': typeof OwnerIndexRoute
  '/tenant/': typeof TenantIndexRoute
  '/account/orders/$orderId': typeof AccountOrdersOrderIdRoute
  '/account/transactions/$transactionId': typeof AccountTransactionsTransactionIdRoute
  '/agent/transactions/$transactionId': typeof AgentTransactionsTransactionIdRoute
  '/account/transactions/': typeof AccountTransactionsIndexRoute
  '/account/viewings/': typeof AccountViewingsIndexRoute
  '/agent/transactions/': typeof AgentTransactionsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/account': typeof AccountRouteWithChildren
  '/cart': typeof CartRoute
  '/checkout': typeof CheckoutRouteWithChildren
  '/search': typeof SearchRoute
  '/account/notifications': typeof AccountNotificationsRoute
  '/account/profile': typeof AccountProfileRoute
  '/admin/catalog': typeof AdminCatalogRoute
  '/admin/categories': typeof AdminCategoriesRoute
  '/admin/checkout': typeof AdminCheckoutRoute
  '/admin/collections': typeof AdminCollectionsRoute
  '/admin/commerce': typeof AdminCommerceRoute
  '/admin/communications': typeof AdminCommunicationsRoute
  '/admin/content': typeof AdminContentRoute
  '/admin/data-transfer': typeof AdminDataTransferRoute
  '/admin/email-templates': typeof AdminEmailTemplatesRoute
  '/admin/feature-cards': typeof AdminFeatureCardsRoute
  '/admin/hero-slides': typeof AdminHeroSlidesRoute
  '/admin/homepage': typeof AdminHomepageRoute
  '/admin/homepage-sections': typeof AdminHomepageSectionsRoute
  '/admin/integrations': typeof AdminIntegrationsRoute
  '/admin/lifestyle-cards': typeof AdminLifestyleCardsRoute
  '/admin/login': typeof AdminLoginRoute
  '/admin/media': typeof AdminMediaRoute
  '/admin/nav-links': typeof AdminNavLinksRoute
  '/admin/newsletter': typeof AdminNewsletterRoute
  '/admin/orders': typeof AdminOrdersRoute
  '/admin/pages': typeof AdminPagesRoute
  '/admin/products': typeof AdminProductsRoute
  '/admin/real-estate': typeof AdminRealEstateRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/admin/site-settings': typeof AdminSiteSettingsRoute
  '/admin/submissions': typeof AdminSubmissionsRoute
  '/admin/tenancy': typeof AdminTenancyRoute
  '/admin/users': typeof AdminUsersRoute
  '/agent/inquiries': typeof AgentInquiriesRoute
  '/agent/maintenance': typeof AgentMaintenanceRoute
  '/agent/tenants': typeof AgentTenantsRoute
  '/agent/viewings': typeof AgentViewingsRoute
  '/bundle/$slug': typeof BundleSlugRoute
  '/checkout/success': typeof CheckoutSuccessRoute
  '/collection/$slug': typeof CollectionSlugRoute
  '/owner/maintenance': typeof OwnerMaintenanceRoute
  '/owner/portfolio': typeof OwnerPortfolioRoute
  '/owner/statements': typeof OwnerStatementsRoute
  '/pages/$slug': typeof PagesSlugRoute
  '/product/$slug': typeof ProductSlugRoute
  '/property/$slug': typeof PropertySlugRoute
  '/tenant/complaints': typeof TenantComplaintsRoute
  '/tenant/documents': typeof TenantDocumentsRoute
  '/tenant/maintenance': typeof TenantMaintenanceRoute
  '/tenant/move-in': typeof TenantMoveInRoute
  '/tenant/notifications': typeof TenantNotificationsRoute
  '/tenant/rent': typeof TenantRentRoute
  '/admin': typeof AdminIndexRoute
  '/agent': typeof AgentIndexRoute
  '/bundles': typeof BundlesIndexRoute
  '/owner': typeof OwnerIndexRoute
  '/tenant': typeof TenantIndexRoute
  '/account/orders/$orderId': typeof AccountOrdersOrderIdRoute
  '/account/transactions/$transactionId': typeof AccountTransactionsTransactionIdRoute
  '/agent/transactions/$transactionId': typeof AgentTransactionsTransactionIdRoute
  '/account/transactions': typeof AccountTransactionsIndexRoute
  '/account/viewings': typeof AccountViewingsIndexRoute
  '/agent/transactions': typeof AgentTransactionsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteRouteWithChildren
  '/agent': typeof AgentRouteRouteWithChildren
  '/owner': typeof OwnerRouteRouteWithChildren
  '/tenant': typeof TenantRouteRouteWithChildren
  '/account': typeof AccountRouteWithChildren
  '/cart': typeof CartRoute
  '/checkout': typeof CheckoutRouteWithChildren
  '/search': typeof SearchRoute
  '/account/notifications': typeof AccountNotificationsRoute
  '/account/profile': typeof AccountProfileRoute
  '/admin/catalog': typeof AdminCatalogRoute
  '/admin/categories': typeof AdminCategoriesRoute
  '/admin/checkout': typeof AdminCheckoutRoute
  '/admin/collections': typeof AdminCollectionsRoute
  '/admin/commerce': typeof AdminCommerceRoute
  '/admin/communications': typeof AdminCommunicationsRoute
  '/admin/content': typeof AdminContentRoute
  '/admin/data-transfer': typeof AdminDataTransferRoute
  '/admin/email-templates': typeof AdminEmailTemplatesRoute
  '/admin/feature-cards': typeof AdminFeatureCardsRoute
  '/admin/hero-slides': typeof AdminHeroSlidesRoute
  '/admin/homepage': typeof AdminHomepageRoute
  '/admin/homepage-sections': typeof AdminHomepageSectionsRoute
  '/admin/integrations': typeof AdminIntegrationsRoute
  '/admin/lifestyle-cards': typeof AdminLifestyleCardsRoute
  '/admin/login': typeof AdminLoginRoute
  '/admin/media': typeof AdminMediaRoute
  '/admin/nav-links': typeof AdminNavLinksRoute
  '/admin/newsletter': typeof AdminNewsletterRoute
  '/admin/orders': typeof AdminOrdersRoute
  '/admin/pages': typeof AdminPagesRoute
  '/admin/products': typeof AdminProductsRoute
  '/admin/real-estate': typeof AdminRealEstateRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/admin/site-settings': typeof AdminSiteSettingsRoute
  '/admin/submissions': typeof AdminSubmissionsRoute
  '/admin/tenancy': typeof AdminTenancyRoute
  '/admin/users': typeof AdminUsersRoute
  '/agent/inquiries': typeof AgentInquiriesRoute
  '/agent/maintenance': typeof AgentMaintenanceRoute
  '/agent/tenants': typeof AgentTenantsRoute
  '/agent/viewings': typeof AgentViewingsRoute
  '/bundle/$slug': typeof BundleSlugRoute
  '/checkout/success': typeof CheckoutSuccessRoute
  '/collection/$slug': typeof CollectionSlugRoute
  '/owner/maintenance': typeof OwnerMaintenanceRoute
  '/owner/portfolio': typeof OwnerPortfolioRoute
  '/owner/statements': typeof OwnerStatementsRoute
  '/pages/$slug': typeof PagesSlugRoute
  '/product/$slug': typeof ProductSlugRoute
  '/property/$slug': typeof PropertySlugRoute
  '/tenant/complaints': typeof TenantComplaintsRoute
  '/tenant/documents': typeof TenantDocumentsRoute
  '/tenant/maintenance': typeof TenantMaintenanceRoute
  '/tenant/move-in': typeof TenantMoveInRoute
  '/tenant/notifications': typeof TenantNotificationsRoute
  '/tenant/rent': typeof TenantRentRoute
  '/admin/': typeof AdminIndexRoute
  '/agent/': typeof AgentIndexRoute
  '/bundles/': typeof BundlesIndexRoute
  '/owner/': typeof OwnerIndexRoute
  '/tenant/': typeof TenantIndexRoute
  '/account/orders/$orderId': typeof AccountOrdersOrderIdRoute
  '/account/transactions/$transactionId': typeof AccountTransactionsTransactionIdRoute
  '/agent/transactions/$transactionId': typeof AgentTransactionsTransactionIdRoute
  '/account/transactions/': typeof AccountTransactionsIndexRoute
  '/account/viewings/': typeof AccountViewingsIndexRoute
  '/agent/transactions/': typeof AgentTransactionsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/agent'
    | '/owner'
    | '/tenant'
    | '/account'
    | '/cart'
    | '/checkout'
    | '/search'
    | '/account/notifications'
    | '/account/profile'
    | '/admin/catalog'
    | '/admin/categories'
    | '/admin/checkout'
    | '/admin/collections'
    | '/admin/commerce'
    | '/admin/communications'
    | '/admin/content'
    | '/admin/data-transfer'
    | '/admin/email-templates'
    | '/admin/feature-cards'
    | '/admin/hero-slides'
    | '/admin/homepage'
    | '/admin/homepage-sections'
    | '/admin/integrations'
    | '/admin/lifestyle-cards'
    | '/admin/login'
    | '/admin/media'
    | '/admin/nav-links'
    | '/admin/newsletter'
    | '/admin/orders'
    | '/admin/pages'
    | '/admin/products'
    | '/admin/real-estate'
    | '/admin/settings'
    | '/admin/site-settings'
    | '/admin/submissions'
    | '/admin/tenancy'
    | '/admin/users'
    | '/agent/inquiries'
    | '/agent/maintenance'
    | '/agent/tenants'
    | '/agent/viewings'
    | '/bundle/$slug'
    | '/checkout/success'
    | '/collection/$slug'
    | '/owner/maintenance'
    | '/owner/portfolio'
    | '/owner/statements'
    | '/pages/$slug'
    | '/product/$slug'
    | '/property/$slug'
    | '/tenant/complaints'
    | '/tenant/documents'
    | '/tenant/maintenance'
    | '/tenant/move-in'
    | '/tenant/notifications'
    | '/tenant/rent'
    | '/admin/'
    | '/agent/'
    | '/bundles/'
    | '/owner/'
    | '/tenant/'
    | '/account/orders/$orderId'
    | '/account/transactions/$transactionId'
    | '/agent/transactions/$transactionId'
    | '/account/transactions/'
    | '/account/viewings/'
    | '/agent/transactions/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/account'
    | '/cart'
    | '/checkout'
    | '/search'
    | '/account/notifications'
    | '/account/profile'
    | '/admin/catalog'
    | '/admin/categories'
    | '/admin/checkout'
    | '/admin/collections'
    | '/admin/commerce'
    | '/admin/communications'
    | '/admin/content'
    | '/admin/data-transfer'
    | '/admin/email-templates'
    | '/admin/feature-cards'
    | '/admin/hero-slides'
    | '/admin/homepage'
    | '/admin/homepage-sections'
    | '/admin/integrations'
    | '/admin/lifestyle-cards'
    | '/admin/login'
    | '/admin/media'
    | '/admin/nav-links'
    | '/admin/newsletter'
    | '/admin/orders'
    | '/admin/pages'
    | '/admin/products'
    | '/admin/real-estate'
    | '/admin/settings'
    | '/admin/site-settings'
    | '/admin/submissions'
    | '/admin/tenancy'
    | '/admin/users'
    | '/agent/inquiries'
    | '/agent/maintenance'
    | '/agent/tenants'
    | '/agent/viewings'
    | '/bundle/$slug'
    | '/checkout/success'
    | '/collection/$slug'
    | '/owner/maintenance'
    | '/owner/portfolio'
    | '/owner/statements'
    | '/pages/$slug'
    | '/product/$slug'
    | '/property/$slug'
    | '/tenant/complaints'
    | '/tenant/documents'
    | '/tenant/maintenance'
    | '/tenant/move-in'
    | '/tenant/notifications'
    | '/tenant/rent'
    | '/admin'
    | '/agent'
    | '/bundles'
    | '/owner'
    | '/tenant'
    | '/account/orders/$orderId'
    | '/account/transactions/$transactionId'
    | '/agent/transactions/$transactionId'
    | '/account/transactions'
    | '/account/viewings'
    | '/agent/transactions'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/agent'
    | '/owner'
    | '/tenant'
    | '/account'
    | '/cart'
    | '/checkout'
    | '/search'
    | '/account/notifications'
    | '/account/profile'
    | '/admin/catalog'
    | '/admin/categories'
    | '/admin/checkout'
    | '/admin/collections'
    | '/admin/commerce'
    | '/admin/communications'
    | '/admin/content'
    | '/admin/data-transfer'
    | '/admin/email-templates'
    | '/admin/feature-cards'
    | '/admin/hero-slides'
    | '/admin/homepage'
    | '/admin/homepage-sections'
    | '/admin/integrations'
    | '/admin/lifestyle-cards'
    | '/admin/login'
    | '/admin/media'
    | '/admin/nav-links'
    | '/admin/newsletter'
    | '/admin/orders'
    | '/admin/pages'
    | '/admin/products'
    | '/admin/real-estate'
    | '/admin/settings'
    | '/admin/site-settings'
    | '/admin/submissions'
    | '/admin/tenancy'
    | '/admin/users'
    | '/agent/inquiries'
    | '/agent/maintenance'
    | '/agent/tenants'
    | '/agent/viewings'
    | '/bundle/$slug'
    | '/checkout/success'
    | '/collection/$slug'
    | '/owner/maintenance'
    | '/owner/portfolio'
    | '/owner/statements'
    | '/pages/$slug'
    | '/product/$slug'
    | '/property/$slug'
    | '/tenant/complaints'
    | '/tenant/documents'
    | '/tenant/maintenance'
    | '/tenant/move-in'
    | '/tenant/notifications'
    | '/tenant/rent'
    | '/admin/'
    | '/agent/'
    | '/bundles/'
    | '/owner/'
    | '/tenant/'
    | '/account/orders/$orderId'
    | '/account/transactions/$transactionId'
    | '/agent/transactions/$transactionId'
    | '/account/transactions/'
    | '/account/viewings/'
    | '/agent/transactions/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRouteRoute: typeof AdminRouteRouteWithChildren
  AgentRouteRoute: typeof AgentRouteRouteWithChildren
  OwnerRouteRoute: typeof OwnerRouteRouteWithChildren
  TenantRouteRoute: typeof TenantRouteRouteWithChildren
  AccountRoute: typeof AccountRouteWithChildren
  CartRoute: typeof CartRoute
  CheckoutRoute: typeof CheckoutRouteWithChildren
  SearchRoute: typeof SearchRoute
  BundleSlugRoute: typeof BundleSlugRoute
  CollectionSlugRoute: typeof CollectionSlugRoute
  PagesSlugRoute: typeof PagesSlugRoute
  ProductSlugRoute: typeof ProductSlugRoute
  PropertySlugRoute: typeof PropertySlugRoute
  BundlesIndexRoute: typeof BundlesIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/search': {
      id: '/search'
      path: '/search'
      fullPath: '/search'
      preLoaderRoute: typeof SearchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/checkout': {
      id: '/checkout'
      path: '/checkout'
      fullPath: '/checkout'
      preLoaderRoute: typeof CheckoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cart': {
      id: '/cart'
      path: '/cart'
      fullPath: '/cart'
      preLoaderRoute: typeof CartRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/account': {
      id: '/account'
      path: '/account'
      fullPath: '/account'
      preLoaderRoute: typeof AccountRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tenant': {
      id: '/tenant'
      path: '/tenant'
      fullPath: '/tenant'
      preLoaderRoute: typeof TenantRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/owner': {
      id: '/owner'
      path: '/owner'
      fullPath: '/owner'
      preLoaderRoute: typeof OwnerRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/agent': {
      id: '/agent'
      path: '/agent'
      fullPath: '/agent'
      preLoaderRoute: typeof AgentRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tenant/': {
      id: '/tenant/'
      path: '/'
      fullPath: '/tenant/'
      preLoaderRoute: typeof TenantIndexRouteImport
      parentRoute: typeof TenantRouteRoute
    }
    '/owner/': {
      id: '/owner/'
      path: '/'
      fullPath: '/owner/'
      preLoaderRoute: typeof OwnerIndexRouteImport
      parentRoute: typeof OwnerRouteRoute
    }
    '/bundles/': {
      id: '/bundles/'
      path: '/bundles'
      fullPath: '/bundles/'
      preLoaderRoute: typeof BundlesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/agent/': {
      id: '/agent/'
      path: '/'
      fullPath: '/agent/'
      preLoaderRoute: typeof AgentIndexRouteImport
      parentRoute: typeof AgentRouteRoute
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/tenant/rent': {
      id: '/tenant/rent'
      path: '/rent'
      fullPath: '/tenant/rent'
      preLoaderRoute: typeof TenantRentRouteImport
      parentRoute: typeof TenantRouteRoute
    }
    '/tenant/notifications': {
      id: '/tenant/notifications'
      path: '/notifications'
      fullPath: '/tenant/notifications'
      preLoaderRoute: typeof TenantNotificationsRouteImport
      parentRoute: typeof TenantRouteRoute
    }
    '/tenant/move-in': {
      id: '/tenant/move-in'
      path: '/move-in'
      fullPath: '/tenant/move-in'
      preLoaderRoute: typeof TenantMoveInRouteImport
      parentRoute: typeof TenantRouteRoute
    }
    '/tenant/maintenance': {
      id: '/tenant/maintenance'
      path: '/maintenance'
      fullPath: '/tenant/maintenance'
      preLoaderRoute: typeof TenantMaintenanceRouteImport
      parentRoute: typeof TenantRouteRoute
    }
    '/tenant/documents': {
      id: '/tenant/documents'
      path: '/documents'
      fullPath: '/tenant/documents'
      preLoaderRoute: typeof TenantDocumentsRouteImport
      parentRoute: typeof TenantRouteRoute
    }
    '/tenant/complaints': {
      id: '/tenant/complaints'
      path: '/complaints'
      fullPath: '/tenant/complaints'
      preLoaderRoute: typeof TenantComplaintsRouteImport
      parentRoute: typeof TenantRouteRoute
    }
    '/property/$slug': {
      id: '/property/$slug'
      path: '/property/$slug'
      fullPath: '/property/$slug'
      preLoaderRoute: typeof PropertySlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/product/$slug': {
      id: '/product/$slug'
      path: '/product/$slug'
      fullPath: '/product/$slug'
      preLoaderRoute: typeof ProductSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pages/$slug': {
      id: '/pages/$slug'
      path: '/pages/$slug'
      fullPath: '/pages/$slug'
      preLoaderRoute: typeof PagesSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/owner/statements': {
      id: '/owner/statements'
      path: '/statements'
      fullPath: '/owner/statements'
      preLoaderRoute: typeof OwnerStatementsRouteImport
      parentRoute: typeof OwnerRouteRoute
    }
    '/owner/portfolio': {
      id: '/owner/portfolio'
      path: '/portfolio'
      fullPath: '/owner/portfolio'
      preLoaderRoute: typeof OwnerPortfolioRouteImport
      parentRoute: typeof OwnerRouteRoute
    }
    '/owner/maintenance': {
      id: '/owner/maintenance'
      path: '/maintenance'
      fullPath: '/owner/maintenance'
      preLoaderRoute: typeof OwnerMaintenanceRouteImport
      parentRoute: typeof OwnerRouteRoute
    }
    '/collection/$slug': {
      id: '/collection/$slug'
      path: '/collection/$slug'
      fullPath: '/collection/$slug'
      preLoaderRoute: typeof CollectionSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/checkout/success': {
      id: '/checkout/success'
      path: '/success'
      fullPath: '/checkout/success'
      preLoaderRoute: typeof CheckoutSuccessRouteImport
      parentRoute: typeof CheckoutRoute
    }
    '/bundle/$slug': {
      id: '/bundle/$slug'
      path: '/bundle/$slug'
      fullPath: '/bundle/$slug'
      preLoaderRoute: typeof BundleSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/agent/viewings': {
      id: '/agent/viewings'
      path: '/viewings'
      fullPath: '/agent/viewings'
      preLoaderRoute: typeof AgentViewingsRouteImport
      parentRoute: typeof AgentRouteRoute
    }
    '/agent/tenants': {
      id: '/agent/tenants'
      path: '/tenants'
      fullPath: '/agent/tenants'
      preLoaderRoute: typeof AgentTenantsRouteImport
      parentRoute: typeof AgentRouteRoute
    }
    '/agent/maintenance': {
      id: '/agent/maintenance'
      path: '/maintenance'
      fullPath: '/agent/maintenance'
      preLoaderRoute: typeof AgentMaintenanceRouteImport
      parentRoute: typeof AgentRouteRoute
    }
    '/agent/inquiries': {
      id: '/agent/inquiries'
      path: '/inquiries'
      fullPath: '/agent/inquiries'
      preLoaderRoute: typeof AgentInquiriesRouteImport
      parentRoute: typeof AgentRouteRoute
    }
    '/admin/users': {
      id: '/admin/users'
      path: '/users'
      fullPath: '/admin/users'
      preLoaderRoute: typeof AdminUsersRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/tenancy': {
      id: '/admin/tenancy'
      path: '/tenancy'
      fullPath: '/admin/tenancy'
      preLoaderRoute: typeof AdminTenancyRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/submissions': {
      id: '/admin/submissions'
      path: '/submissions'
      fullPath: '/admin/submissions'
      preLoaderRoute: typeof AdminSubmissionsRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/site-settings': {
      id: '/admin/site-settings'
      path: '/site-settings'
      fullPath: '/admin/site-settings'
      preLoaderRoute: typeof AdminSiteSettingsRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/settings': {
      id: '/admin/settings'
      path: '/settings'
      fullPath: '/admin/settings'
      preLoaderRoute: typeof AdminSettingsRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/real-estate': {
      id: '/admin/real-estate'
      path: '/real-estate'
      fullPath: '/admin/real-estate'
      preLoaderRoute: typeof AdminRealEstateRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/products': {
      id: '/admin/products'
      path: '/products'
      fullPath: '/admin/products'
      preLoaderRoute: typeof AdminProductsRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/pages': {
      id: '/admin/pages'
      path: '/pages'
      fullPath: '/admin/pages'
      preLoaderRoute: typeof AdminPagesRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/orders': {
      id: '/admin/orders'
      path: '/orders'
      fullPath: '/admin/orders'
      preLoaderRoute: typeof AdminOrdersRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/newsletter': {
      id: '/admin/newsletter'
      path: '/newsletter'
      fullPath: '/admin/newsletter'
      preLoaderRoute: typeof AdminNewsletterRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/nav-links': {
      id: '/admin/nav-links'
      path: '/nav-links'
      fullPath: '/admin/nav-links'
      preLoaderRoute: typeof AdminNavLinksRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/media': {
      id: '/admin/media'
      path: '/media'
      fullPath: '/admin/media'
      preLoaderRoute: typeof AdminMediaRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/login': {
      id: '/admin/login'
      path: '/login'
      fullPath: '/admin/login'
      preLoaderRoute: typeof AdminLoginRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/lifestyle-cards': {
      id: '/admin/lifestyle-cards'
      path: '/lifestyle-cards'
      fullPath: '/admin/lifestyle-cards'
      preLoaderRoute: typeof AdminLifestyleCardsRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/integrations': {
      id: '/admin/integrations'
      path: '/integrations'
      fullPath: '/admin/integrations'
      preLoaderRoute: typeof AdminIntegrationsRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/homepage-sections': {
      id: '/admin/homepage-sections'
      path: '/homepage-sections'
      fullPath: '/admin/homepage-sections'
      preLoaderRoute: typeof AdminHomepageSectionsRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/homepage': {
      id: '/admin/homepage'
      path: '/homepage'
      fullPath: '/admin/homepage'
      preLoaderRoute: typeof AdminHomepageRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/hero-slides': {
      id: '/admin/hero-slides'
      path: '/hero-slides'
      fullPath: '/admin/hero-slides'
      preLoaderRoute: typeof AdminHeroSlidesRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/feature-cards': {
      id: '/admin/feature-cards'
      path: '/feature-cards'
      fullPath: '/admin/feature-cards'
      preLoaderRoute: typeof AdminFeatureCardsRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/email-templates': {
      id: '/admin/email-templates'
      path: '/email-templates'
      fullPath: '/admin/email-templates'
      preLoaderRoute: typeof AdminEmailTemplatesRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/data-transfer': {
      id: '/admin/data-transfer'
      path: '/data-transfer'
      fullPath: '/admin/data-transfer'
      preLoaderRoute: typeof AdminDataTransferRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/content': {
      id: '/admin/content'
      path: '/content'
      fullPath: '/admin/content'
      preLoaderRoute: typeof AdminContentRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/communications': {
      id: '/admin/communications'
      path: '/communications'
      fullPath: '/admin/communications'
      preLoaderRoute: typeof AdminCommunicationsRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/commerce': {
      id: '/admin/commerce'
      path: '/commerce'
      fullPath: '/admin/commerce'
      preLoaderRoute: typeof AdminCommerceRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/collections': {
      id: '/admin/collections'
      path: '/collections'
      fullPath: '/admin/collections'
      preLoaderRoute: typeof AdminCollectionsRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/checkout': {
      id: '/admin/checkout'
      path: '/checkout'
      fullPath: '/admin/checkout'
      preLoaderRoute: typeof AdminCheckoutRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/categories': {
      id: '/admin/categories'
      path: '/categories'
      fullPath: '/admin/categories'
      preLoaderRoute: typeof AdminCategoriesRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/catalog': {
      id: '/admin/catalog'
      path: '/catalog'
      fullPath: '/admin/catalog'
      preLoaderRoute: typeof AdminCatalogRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/account/profile': {
      id: '/account/profile'
      path: '/profile'
      fullPath: '/account/profile'
      preLoaderRoute: typeof AccountProfileRouteImport
      parentRoute: typeof AccountRoute
    }
    '/account/notifications': {
      id: '/account/notifications'
      path: '/notifications'
      fullPath: '/account/notifications'
      preLoaderRoute: typeof AccountNotificationsRouteImport
      parentRoute: typeof AccountRoute
    }
    '/agent/transactions/': {
      id: '/agent/transactions/'
      path: '/transactions'
      fullPath: '/agent/transactions/'
      preLoaderRoute: typeof AgentTransactionsIndexRouteImport
      parentRoute: typeof AgentRouteRoute
    }
    '/account/viewings/': {
      id: '/account/viewings/'
      path: '/viewings'
      fullPath: '/account/viewings/'
      preLoaderRoute: typeof AccountViewingsIndexRouteImport
      parentRoute: typeof AccountRoute
    }
    '/account/transactions/': {
      id: '/account/transactions/'
      path: '/transactions'
      fullPath: '/account/transactions/'
      preLoaderRoute: typeof AccountTransactionsIndexRouteImport
      parentRoute: typeof AccountRoute
    }
    '/agent/transactions/$transactionId': {
      id: '/agent/transactions/$transactionId'
      path: '/transactions/$transactionId'
      fullPath: '/agent/transactions/$transactionId'
      preLoaderRoute: typeof AgentTransactionsTransactionIdRouteImport
      parentRoute: typeof AgentRouteRoute
    }
    '/account/transactions/$transactionId': {
      id: '/account/transactions/$transactionId'
      path: '/transactions/$transactionId'
      fullPath: '/account/transactions/$transactionId'
      preLoaderRoute: typeof AccountTransactionsTransactionIdRouteImport
      parentRoute: typeof AccountRoute
    }
    '/account/orders/$orderId': {
      id: '/account/orders/$orderId'
      path: '/orders/$orderId'
      fullPath: '/account/orders/$orderId'
      preLoaderRoute: typeof AccountOrdersOrderIdRouteImport
      parentRoute: typeof AccountRoute
    }
  }
}

interface AdminRouteRouteChildren {
  AdminCatalogRoute: typeof AdminCatalogRoute
  AdminCategoriesRoute: typeof AdminCategoriesRoute
  AdminCheckoutRoute: typeof AdminCheckoutRoute
  AdminCollectionsRoute: typeof AdminCollectionsRoute
  AdminCommerceRoute: typeof AdminCommerceRoute
  AdminCommunicationsRoute: typeof AdminCommunicationsRoute
  AdminContentRoute: typeof AdminContentRoute
  AdminDataTransferRoute: typeof AdminDataTransferRoute
  AdminEmailTemplatesRoute: typeof AdminEmailTemplatesRoute
  AdminFeatureCardsRoute: typeof AdminFeatureCardsRoute
  AdminHeroSlidesRoute: typeof AdminHeroSlidesRoute
  AdminHomepageRoute: typeof AdminHomepageRoute
  AdminHomepageSectionsRoute: typeof AdminHomepageSectionsRoute
  AdminIntegrationsRoute: typeof AdminIntegrationsRoute
  AdminLifestyleCardsRoute: typeof AdminLifestyleCardsRoute
  AdminLoginRoute: typeof AdminLoginRoute
  AdminMediaRoute: typeof AdminMediaRoute
  AdminNavLinksRoute: typeof AdminNavLinksRoute
  AdminNewsletterRoute: typeof AdminNewsletterRoute
  AdminOrdersRoute: typeof AdminOrdersRoute
  AdminPagesRoute: typeof AdminPagesRoute
  AdminProductsRoute: typeof AdminProductsRoute
  AdminRealEstateRoute: typeof AdminRealEstateRoute
  AdminSettingsRoute: typeof AdminSettingsRoute
  AdminSiteSettingsRoute: typeof AdminSiteSettingsRoute
  AdminSubmissionsRoute: typeof AdminSubmissionsRoute
  AdminTenancyRoute: typeof AdminTenancyRoute
  AdminUsersRoute: typeof AdminUsersRoute
  AdminIndexRoute: typeof AdminIndexRoute
}

const AdminRouteRouteChildren: AdminRouteRouteChildren = {
  AdminCatalogRoute: AdminCatalogRoute,
  AdminCategoriesRoute: AdminCategoriesRoute,
  AdminCheckoutRoute: AdminCheckoutRoute,
  AdminCollectionsRoute: AdminCollectionsRoute,
  AdminCommerceRoute: AdminCommerceRoute,
  AdminCommunicationsRoute: AdminCommunicationsRoute,
  AdminContentRoute: AdminContentRoute,
  AdminDataTransferRoute: AdminDataTransferRoute,
  AdminEmailTemplatesRoute: AdminEmailTemplatesRoute,
  AdminFeatureCardsRoute: AdminFeatureCardsRoute,
  AdminHeroSlidesRoute: AdminHeroSlidesRoute,
  AdminHomepageRoute: AdminHomepageRoute,
  AdminHomepageSectionsRoute: AdminHomepageSectionsRoute,
  AdminIntegrationsRoute: AdminIntegrationsRoute,
  AdminLifestyleCardsRoute: AdminLifestyleCardsRoute,
  AdminLoginRoute: AdminLoginRoute,
  AdminMediaRoute: AdminMediaRoute,
  AdminNavLinksRoute: AdminNavLinksRoute,
  AdminNewsletterRoute: AdminNewsletterRoute,
  AdminOrdersRoute: AdminOrdersRoute,
  AdminPagesRoute: AdminPagesRoute,
  AdminProductsRoute: AdminProductsRoute,
  AdminRealEstateRoute: AdminRealEstateRoute,
  AdminSettingsRoute: AdminSettingsRoute,
  AdminSiteSettingsRoute: AdminSiteSettingsRoute,
  AdminSubmissionsRoute: AdminSubmissionsRoute,
  AdminTenancyRoute: AdminTenancyRoute,
  AdminUsersRoute: AdminUsersRoute,
  AdminIndexRoute: AdminIndexRoute,
}

const AdminRouteRouteWithChildren = AdminRouteRoute._addFileChildren(
  AdminRouteRouteChildren,
)

interface AgentRouteRouteChildren {
  AgentInquiriesRoute: typeof AgentInquiriesRoute
  AgentMaintenanceRoute: typeof AgentMaintenanceRoute
  AgentTenantsRoute: typeof AgentTenantsRoute
  AgentViewingsRoute: typeof AgentViewingsRoute
  AgentIndexRoute: typeof AgentIndexRoute
  AgentTransactionsTransactionIdRoute: typeof AgentTransactionsTransactionIdRoute
  AgentTransactionsIndexRoute: typeof AgentTransactionsIndexRoute
}

const AgentRouteRouteChildren: AgentRouteRouteChildren = {
  AgentInquiriesRoute: AgentInquiriesRoute,
  AgentMaintenanceRoute: AgentMaintenanceRoute,
  AgentTenantsRoute: AgentTenantsRoute,
  AgentViewingsRoute: AgentViewingsRoute,
  AgentIndexRoute: AgentIndexRoute,
  AgentTransactionsTransactionIdRoute: AgentTransactionsTransactionIdRoute,
  AgentTransactionsIndexRoute: AgentTransactionsIndexRoute,
}

const AgentRouteRouteWithChildren = AgentRouteRoute._addFileChildren(
  AgentRouteRouteChildren,
)

interface OwnerRouteRouteChildren {
  OwnerMaintenanceRoute: typeof OwnerMaintenanceRoute
  OwnerPortfolioRoute: typeof OwnerPortfolioRoute
  OwnerStatementsRoute: typeof OwnerStatementsRoute
  OwnerIndexRoute: typeof OwnerIndexRoute
}

const OwnerRouteRouteChildren: OwnerRouteRouteChildren = {
  OwnerMaintenanceRoute: OwnerMaintenanceRoute,
  OwnerPortfolioRoute: OwnerPortfolioRoute,
  OwnerStatementsRoute: OwnerStatementsRoute,
  OwnerIndexRoute: OwnerIndexRoute,
}

const OwnerRouteRouteWithChildren = OwnerRouteRoute._addFileChildren(
  OwnerRouteRouteChildren,
)

interface TenantRouteRouteChildren {
  TenantComplaintsRoute: typeof TenantComplaintsRoute
  TenantDocumentsRoute: typeof TenantDocumentsRoute
  TenantMaintenanceRoute: typeof TenantMaintenanceRoute
  TenantMoveInRoute: typeof TenantMoveInRoute
  TenantNotificationsRoute: typeof TenantNotificationsRoute
  TenantRentRoute: typeof TenantRentRoute
  TenantIndexRoute: typeof TenantIndexRoute
}

const TenantRouteRouteChildren: TenantRouteRouteChildren = {
  TenantComplaintsRoute: TenantComplaintsRoute,
  TenantDocumentsRoute: TenantDocumentsRoute,
  TenantMaintenanceRoute: TenantMaintenanceRoute,
  TenantMoveInRoute: TenantMoveInRoute,
  TenantNotificationsRoute: TenantNotificationsRoute,
  TenantRentRoute: TenantRentRoute,
  TenantIndexRoute: TenantIndexRoute,
}

const TenantRouteRouteWithChildren = TenantRouteRoute._addFileChildren(
  TenantRouteRouteChildren,
)

interface AccountRouteChildren {
  AccountNotificationsRoute: typeof AccountNotificationsRoute
  AccountProfileRoute: typeof AccountProfileRoute
  AccountOrdersOrderIdRoute: typeof AccountOrdersOrderIdRoute
  AccountTransactionsTransactionIdRoute: typeof AccountTransactionsTransactionIdRoute
  AccountTransactionsIndexRoute: typeof AccountTransactionsIndexRoute
  AccountViewingsIndexRoute: typeof AccountViewingsIndexRoute
}

const AccountRouteChildren: AccountRouteChildren = {
  AccountNotificationsRoute: AccountNotificationsRoute,
  AccountProfileRoute: AccountProfileRoute,
  AccountOrdersOrderIdRoute: AccountOrdersOrderIdRoute,
  AccountTransactionsTransactionIdRoute: AccountTransactionsTransactionIdRoute,
  AccountTransactionsIndexRoute: AccountTransactionsIndexRoute,
  AccountViewingsIndexRoute: AccountViewingsIndexRoute,
}

const AccountRouteWithChildren =
  AccountRoute._addFileChildren(AccountRouteChildren)

interface CheckoutRouteChildren {
  CheckoutSuccessRoute: typeof CheckoutSuccessRoute
}

const CheckoutRouteChildren: CheckoutRouteChildren = {
  CheckoutSuccessRoute: CheckoutSuccessRoute,
}

const CheckoutRouteWithChildren = CheckoutRoute._addFileChildren(
  CheckoutRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRouteRoute: AdminRouteRouteWithChildren,
  AgentRouteRoute: AgentRouteRouteWithChildren,
  OwnerRouteRoute: OwnerRouteRouteWithChildren,
  TenantRouteRoute: TenantRouteRouteWithChildren,
  AccountRoute: AccountRouteWithChildren,
  CartRoute: CartRoute,
  CheckoutRoute: CheckoutRouteWithChildren,
  SearchRoute: SearchRoute,
  BundleSlugRoute: BundleSlugRoute,
  CollectionSlugRoute: CollectionSlugRoute,
  PagesSlugRoute: PagesSlugRoute,
  ProductSlugRoute: ProductSlugRoute,
  PropertySlugRoute: PropertySlugRoute,
  BundlesIndexRoute: BundlesIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
